---

- name: "Test playbook run"

  hosts: all
  become: true
  become_method: su
  become_user: root
  tasks:
    - name: "Installing and enabling nginx if needed"
      
      apt: "name=nginx state=latest"
      notify:
        - nginx systemd

    - name: "Copy build to the webservers"

      copy: "src=./build/ dest=/var/www/html/"