---

- name: "Test playbook run"
  hosts: all
  become: yes

  vars:
    source_dir: /var/lib/jenkins/workspace/react-gallery/build/
    destin_dir: /var/www/html/

  tasks:
  - name: "Check and print OS"
    debug: var=ansible_os_family

  - name: "Install Nginx Web Server on Debian"
    apt: "name=nginx state=latest"
    when: ansible_os_family == "Debian"

  - name: "Install Nginx Web Server on CentOS"
    yum: "name=nginx state=latest"
    when: ansible_os_family != "Debian"

  - name: "Copy build to the Web Server"
    copy: "src={{ source_die }} dest={{ dest_dir }} mode=0555"
    notyfy: Restart Nginx

  - name: "Start Web Server service"
    service: "name=nginx state=started enabled=yes"

  handlers:
   - name: Restart Nginx 
     service: "name=nginx state=restarted"